name: Morning Bot

on:
  schedule:
    - cron: "0 0,15 * * *" # 0時 (9AM JST) と 15時 (0AM JST)
  workflow_dispatch:
jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      SLACK_USERNAME: sleeping bot
      SLACK_ICON: https://raw.githubusercontent.com/tkm-developer/my-repo/main/icon/icon2.jpg
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Slack Message
        id: set-message
        run: |
          HOUR=$(date +'%H')
          if [ "$HOUR" -eq 0 ]; then
            echo "slack_title=おはよう" >> $GITHUB_ENV
            echo "slack_message=朝です" >> $GITHUB_ENV
          elif [ "$HOUR" -eq 15 ]; then
            echo "slack_title=おやすみ" >> $GITHUB_ENV
            echo "slack_message=夜です" >> $GITHUB_ENV
          else
            echo "slack_title=不明" >> $GITHUB_ENV
            echo "slack_message=時間設定に問題があります" >> $GITHUB_ENV
          fi

      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        with:
          title: ${{ env.slack_title }}
          text: ${{ env.slack_message }}
        if: ${{ success() }}

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        with:
          title: "失敗"
          text: "送信に失敗しました"
        if: ${{ failure() }}
